export const PRESETS = [
  {
    id: "hyderabad-snacks-home",
    name: "Hyderabad Homemade Healthy Snacks (Featured Signature Demo)",
    badge: "Signature Demo ★",
    sector: "food-beverage",
    sectorLabel: "Food & Healthy Snacks",
    business_name: "NutriBites Artisanal Kitchen",
    business_type: "Homemade Healthy Snacks & Millet Treats",
    business_start_mode: "Home-Based",
    location: "Kondapur, Hyderabad",
    locality: "Kondapur",
    city: "Hyderabad",
    state: "Telangana",
    capital: 300000,
    currency: "INR",
    capitalDisplay: "₹3,00,000",
    primary_usp: "100% natural, preservative-free artisanal millet snacks freshly prepared",
    objective: "Launch a profitable home-based healthy snack brand with zero store rent, acquiring first 10 customers in 7 days and 50+ recurring buyers in 30 days.",
    risk_preference: "Moderate",
    time_horizon: "3 years",
    experience_level: "Beginner",
    target_customer: "Health-conscious tech professionals in Kondapur/Hitech City, fitness enthusiasts, and apartment communities seeking guilt-free snacks",
    constraints: "Zero commercial lease deposit; channel capital strictly into high-grade packaging, fresh ingredients, and neighborhood sampling."
  },
  {
    id: "hyderabad-food",
    name: "Hyderabad Artisanal Cloud Kitchen & Cafe",
    badge: "Cloud Kitchen",
    sector: "food-beverage",
    sectorLabel: "Food & Beverage",
    business_name: "Artisan Gourmet Bowls & Brew",
    business_type: "Artisanal Cloud Kitchen & Quick Service Cafe",
    business_start_mode: "Physical Store",
    location: "Hyderabad",
    capital: 1000000,
    currency: "INR",
    capitalDisplay: "₹10,00,000",
    objective: "Launch a high-margin quick service kitchen in Hitec City / Madhapur with strong delivery unit economics and 3-year profitability.",
    risk_preference: "Moderate",
    time_horizon: "3 years",
    experience_level: "Beginner",
    target_customer: "Corporate tech workforce in Hitec City, high-density residential towers, and young weekend delivery diners",
    constraints: "Cap pre-revenue kitchen equipment and setup to 40% of capital; preserve 3 months of fixed operating burn in liquid cash."
  },
  {
    id: "bengaluru-saas",
    name: "Bengaluru AI Workflow Automation (B2B SaaS)",
    badge: "Tech Startup",
    sector: "software-saas",
    sectorLabel: "Software & SaaS",
    business_name: "FlowSynapse AI",
    business_type: "Agentic Document & Invoice Workflow SaaS for SMEs",
    location: "Bengaluru",
    capital: 1500000,
    currency: "INR",
    capitalDisplay: "?15,00,000",
    objective: "Build and scale an AI-native B2B SaaS tool for mid-market logistics companies to achieve $10k MRR within 18 months.",
    risk_preference: "Aggressive",
    time_horizon: "3 years",
    experience_level: "Intermediate",
    target_customer: "Operations heads and finance teams at mid-sized logistics and distribution firms",
    constraints: "Lean engineering team of 2 devs, prioritize low-cost cloud infrastructure with serverless architecture."
  },
  {
    id: "mumbai-retail",
    name: "Mumbai Sustainable Lifestyle Store (Omnichannel Retail)",
    badge: "Lifestyle Retail",
    sector: "retail",
    sectorLabel: "Retail & E-commerce",
    business_name: "Aura Earth Lifestyle",
    business_type: "Boutique Eco-Friendly Home Decor & Sustainable Fashion",
    location: "Mumbai",
    capital: 1200000,
    currency: "INR",
    capitalDisplay: "?12,00,000",
    objective: "Establish a boutique storefront in Bandra supported by an active Shopify D2C channel.",
    risk_preference: "Moderate",
    time_horizon: "3 years",
    experience_level: "Beginner",
    target_customer: "Conscious urban consumers and home-styling enthusiasts in Mumbai metropolitan area",
    constraints: "Consignment agreements with local artisan clusters to minimize upfront inventory risk."
  },
  {
    id: "pune-clinic",
    name: "Pune Preventive Diagnostic Hub (Healthcare)",
    badge: "Healthcare",
    sector: "healthcare",
    sectorLabel: "Healthcare & Wellness",
    business_name: "PulseCare Diagnostics",
    business_type: "Preventive Health Screening & Home Sample Collection Hub",
    location: "Pune",
    capital: 2500000,
    currency: "INR",
    capitalDisplay: "?25,00,000",
    objective: "Establish a high-trust neighborhood diagnostic clinic with automated digital reports.",
    risk_preference: "Conservative",
    time_horizon: "5 years",
    experience_level: "Intermediate",
    target_customer: "Families, senior citizens, and health-conscious professionals",
    constraints: "Clinical Establishment Act clearances mandatory prior to lease lock-in."
  }
];
